// data-testid
export enum TestID {
  ADD_CATEGORY_BUTTON = 'add-category-button',
  CATEGORY_EDIT = 'category-edit',
  CATEGORY_LIST_DIV = 'category-list-div',
  CATEGORY_OPTIONS_NAV = 'category-options-nav',
  CATEGORY_OPTION_RENAME = 'category-options-rename',
  CATEGORY_OPTION_DELETE_PERMANENTLY = 'category-option-delete-permanently',
  EDIT_CATEGORY = 'edit-category',
  EMPTY_TRASH_BUTTON = 'empty-trash-button',
  FOLDER_ALL_NOTES = 'all-notes',
  FOLDER_FAVORITES = 'favorites',
  FOLDER_TRASH = 'trash',
  NEW_CATEGORY_FORM = 'new-category-form',
  NEW_CATEGORY_INPUT = 'new-category-label',
  NOTE_LIST = 'note-list',
  NOTE_LIST_ITEM = 'note-list-item-',
  NOTE_OPTIONS_DIV = 'note-options-div-',
  NOTE_OPTIONS_NAV = 'note-options-nav',
  NOTE_OPTION_DELETE_PERMANENTLY = 'note-option-delete-permanently',
  NOTE_OPTION_DOWNLOAD = 'note-option-download',
  NOTE_OPTION_FAVORITE = 'note-option-favorite',
  NOTE_OPTION_REMOVE_CATEGORY = 'note-option-remove-category',
  NOTE_OPTION_RESTORE_FROM_TRASH = 'note-option-restore-from-trash',
  NOTE_OPTION_TRASH = 'note-option-trash',
  NOTE_SEARCH = 'note-search',
  NOTE_TITLE = 'note-title-',
  MOVE_TO_CATEGORY = 'note-options-move-to-category-select',
  REMOVE_CATEGORY = 'remove-category',
  MOVE_CATEGORY = 'move-category',
  SIDEBAR_ACTION_CREATE_NEW_NOTE = 'sidebar-action-create-new-note',
  SIDEBAR_ACTION_SETTINGS = 'sidebar-action-settings',
  SIDEBAR_ACTION_SYNC_NOTES = 'sidebar-action-sync-notes',
  SCRATCHPAD = 'scratchpad',
}
