export enum ActionType {
  ADD_NOTE = 'ADD_NOTE',
  SWAP_NOTE = 'SWAP_NOTE',
  UPDATE_NOTE = 'UPDATE_NOTE',
  DELETE_NOTE = 'DELETE_NOTE',
  LOAD_NOTES = 'LOAD_NOTES',
  LOAD_NOTES_SUCCESS = 'LOAD_NOTES_SUCCESS',
  LOAD_NOTES_ERROR = 'LOAD_NOTES_ERROR',
  RENDER_NOTES = 'RENDER_NOTES',
}
